# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/BestKai/SJRouterPrivatePod.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SJModuleE' do
 
end
